- .dccache
- .eslintrc.js
- .prettierrc
- .vscode/settings.json
- package-lock.json
- package.json
- src/AppSetup.tsx
Add support for prettier users, tested and it works on my machine. Fixes #13
> Add prettier support

- src/AppSetup.tsx
- src/components/PerProjectChart.tsx
Very minor, but essential fixes.
> Minor fixes to perProjectChart scaling & mobile menu

- src/hooks/useFriends.ts
Depends on https://github.com/Testaustime/testaustime-backend/pull/12
> Use the coding data from response when adding a new friend

- src/AppSetup.tsx
Don't ask any questions. I have no answers.
Patches #44.
> fix: Correction to stupid CSS

- package-lock.json
- package.json
- src/components/Dashboard.tsx
> Add All time date range

- src/components/Friendboard.tsx
- src/components/Leaderboard/JoinLeaderboardModal.tsx
- src/components/pages/LeaderboardsPage.tsx
Take the `code` url parameter on friend and leaderboard page loads and autofill them for easy joining via links.
> feat: url join code

- vercel.json
https://www.querythreads.com/vercel-vite-404-not-found/
> fix: rewrite all paths to root /

- index.html
> add: seo metatags

- src/components/Dashboard.tsx
- src/components/DefaultDayRangeSelector/DefaultDayRangeSelector.stories.tsx
- src/components/DefaultDayRangeSelector/DefaultDayRangeSelector.tsx
- src/components/pages/ProfilePage.tsx
- src/contexts/SettingsContext.ts
- src/hooks/useSettings.ts
- src/i18n/en/index.ts
- src/i18n/fi/index.ts
- src/i18n/i18n-types.ts
> feat: add selector for default day range to settings, fixes #66

- .typesafe-i18n.json
- src/components/ChangePasswordForm/ChangePasswordForm.stories.tsx
- src/components/ChangePasswordForm/ChangePasswordForm.tsx
- src/components/ChangePasswordForm/index.tsx
- src/components/pages/ProfilePage.tsx
- src/hooks/UseAuthentication/useAuthentication.ts
- src/i18n/en/index.ts
- src/i18n/fi/index.ts
- src/i18n/i18n-types.ts
> feat(auth): add ability to change password, fixes #8

- src/components/DailyCodingTimeChart.tsx
> fix: fix tick size discrepancy, fixes #148

- src/components/Dashboard.tsx
- src/components/friends/FriendList.tsx
- src/components/pages/MainPage.tsx
- src/hooks/useActivityData.ts
- src/i18n/en/index.ts
- src/i18n/fi/index.ts
- src/i18n/i18n-types.ts
> feat(friends): add ability to see friends' dashboard

- package-lock.json
- package.json
- src/AppSetup.tsx
- src/hooks/UseAuthentication/useAuthentication.test.tsx
- src/hooks/UseAuthentication/useAuthentication.ts
- src/hooks/useActivityData.ts
- src/hooks/useFriends.ts
- src/hooks/useLeaderboards.ts
> Add react query

- src/components/leaderboard/JoinLeaderboardModal.tsx
- src/i18n/en/index.ts
- src/i18n/fi/index.ts
- src/i18n/i18n-types.ts
> feat: show better error message when trying to join a non-existent leaderboard

- src/components/ChangePasswordForm/ChangePasswordForm.tsx
- src/components/TokenField/TokenField.tsx
- src/components/friends/AddFriendForm.tsx
- src/components/friends/FriendList.tsx
- src/components/leaderboard/CreateLeaderboardModal.tsx
- src/components/leaderboard/JoinLeaderboardModal.tsx
- src/components/pages/LeaderboardsPage.tsx
- src/components/pages/LoginPage.tsx
- src/components/pages/RegistrationPage.tsx
- src/hooks/useFriends.ts
- src/hooks/useLeaderboards.ts
- src/i18n/en/index.ts
- src/i18n/fi/index.ts
- src/i18n/i18n-types.ts
- src/lib/errorHandling/errorHandler.ts
- src/utils/notificationErrorHandler.ts
> Better errors

- .typesafe-i18n.json
- src/components/Dashboard.tsx
> fix(dashboard): show time range selector always, fixes #176

- .typesafe-i18n.json
- src/components/LoginForm/LoginForm.stories.tsx
- src/components/LoginForm/LoginForm.tsx
- src/components/LoginForm/index.tsx
- src/components/forms/FormikPasswordInput.tsx
- src/components/forms/FormikTextInput.tsx
- src/components/pages/LoginPage.tsx
> Show error on login form only if the field was touched

- src/components/Dashboard.tsx
- src/components/EditProjectModal/EditProjectModal.tsx
- src/components/EditProjectModal/index.tsx
- src/components/TopProjects/ProjectEntry.tsx
- src/components/TopProjects/TopProjects.tsx
- src/hooks/useActivities.tsx
- src/i18n/en/index.ts
- src/i18n/fi/index.ts
- src/i18n/i18n-types.ts
> Implement project name editing

- .typesafe-i18n.json
- src/components/Footer/Footer.tsx
- src/components/LanguageSelector/LanguageSelector.stories.tsx
- src/components/LanguageSelector/LanguageSelector.tsx
- src/components/LoginForm/LoginForm.tsx
- src/components/pages/LoginPage.tsx
- src/components/pages/MainPage.tsx
- src/components/pages/RegistrationPage.tsx
- src/i18n/en/index.ts
- src/i18n/fi/index.ts
- src/i18n/i18n-types.ts
- src/i18n/i18n-util.ts
> Add language selector to footer

- src/hooks/useSettings.ts
> [Fix] Theme takes 2 clicks to toggle at first time load.

- src/components/DailyCodingTimeChart/DailyCodingTimeChart.stories.tsx
- src/components/DailyCodingTimeChart/DailyCodingTimeChart.tsx
- src/components/DailyCodingTimeChart/index.tsx
- src/components/Dashboard.tsx
> fix: fix day chart when all days have 0, and refactor it a bit

- src/components/ConfirmAccountDeletionModal/ConfirmAccountDeletionModal.tsx
- src/components/ConfirmAccountDeletionModal/index.tsx
- src/components/pages/ProfilePage.tsx
- src/hooks/useAccount.ts
- src/i18n/en/index.ts
- src/i18n/fi/index.ts
- src/i18n/i18n-types.ts
> feat: add button to delete account

- public/locales/en/common.json
- public/locales/fi/common.json
- src/hooks/useAuthentication.ts
- src/pages/register/index.tsx
> fix: show correct error message when rate limited during registration

- src/components/TopProjects/ProjectEntry.tsx
- src/components/friends/FriendList.tsx
- src/pages/leaderboards/index.tsx
- src/pages/profile/index.tsx
> fix: change all modals to have correct semantic HTML in titles

- src/pages/_app.tsx
- src/pages/_document.tsx
> Added favicon and page title

- public/locales/en/common.json
- public/locales/fi/common.json
- src/app/[locale]/leaderboards/[name]/actions.ts
- src/app/[locale]/profile/AuthTokenField.tsx
- src/app/[locale]/profile/actions.ts
- src/app/[locale]/register/actions.ts
- src/components/LoginForm/actions.ts
- src/components/friends/actions.ts
- src/components/leaderboard/actions.ts
- src/types.ts
- src/utils/authUtils.ts
Don't merge until the new backend is also deployed
> Use secure access token for the actions that require it

- public/locales/en/common.json
- public/locales/fi/common.json
- src/api/leaderboardApi.ts
- src/app/[locale]/leaderboards/page.tsx
> feat: show error message if loading leaderboards fails

- src/components/NavigationMenuDropdown.tsx
> Make menu dropdown accessible with keyboard

- src/components/Dashboard.tsx
- src/components/MonthlyCodingTimeChart/MonthlyCodingTimeChart.tsx
- src/components/MonthlyCodingTimeChart/index.tsx
> Add monthly bucket chart if there are too many days
